#!/bin/bash

if [ -d ~/.rbenv ]; then
    echo "rbenv is already installed"
else
    echo "Installing rbenv"
    git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
    git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
    echo "rbenv install -l to install new versions"
fi

if [ -d ~/.asdf ]; then
    echo "asdf is already installed"
else
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.2.1
    ~/.asdf/bin/asdf plugin-add python https://github.com/tuvistavie/asdf-python.git
    ~/.asdf/bin/asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    ~/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    ~/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
    ~/.asdf/bin/asdf plugin-add lua https://github.com/Stratus3D/asdf-lua.git
fi


