#! /bin/bash

if [ -d ~/.emacs.d ]; then
    echo "~/emacs.d alreadt exists" 1>&2
else
    echo "Installing spacemacs"
    git clone --recursive https://github.com/syl20bnr/spacemacs.git ~/.emacs.d
fi

if [ -d ~/.oh-my-zsh ]; then
    echo "oh-my-zsh is already installed"
else
    echo "Installing oh-my-zsh"
    git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    . ~/.zshrc
fi

if [ -d ~/.bash_it ]; then
    echo "bash-it is already installed"
else
    echo "Installing bash-it"
    git clone --depth=1 https://github.com/Bash-it/bash-it.git ~/.bash_it
fi

if [ -d ~/.vimperator/colors ]; then
    echo "vimperator-colors is already installed"
else
    echo "Installing vimperator-colors"
    git clone https://github.com/vimpr/vimperator-colors.git ~/.vimperator/colors
fi
