#! /bin/bash

if [ -d ~/.emacs.d ]; then
    echo "~/.emacs.d already exists" 1>&2
else
    echo "Installing emacs development environment"
    git clone --recursive git@github.com:gjhenrique/zezin.emacs.git ~/.emacs.d
fi

if [ -d ~/.oh-my-zsh ]; then
    echo "oh-my-zsh is already installed"
else
    echo "Installing oh-my-zsh"
    git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
    . ~/.zshrc
fi

if [ -e ~/.git-prompt.sh ]; then
    echo "git-prompt is already installed"
else
    echo "Installing git-prompt"
    curl -o ~/.git-prompt.sh https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
fi

if [ -e ~/.tmux-themepack ]; then
    echo "tmux-themepack is already installed"
else
    echo "Installing tmux-themepack"
    git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
fi

if [ -e ~/.fzf ]; then
    echo "fzf is already installed"
else
    echo "Installing fzf"
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --no-update-rc --no-bash --no-zsh --no-fish
fi
