#! /bin/bash

mkdir -p ~/Projects/elisp
if [ -f ~/.emacs ]; then
    echo "~/.emacs already exists" 1>&2
else
    echo "Installing chemacs"
    git clone https://github.com/plexus/chemacs.git ~/Projects/elisp/chemacs
    bash ~/Projects/elisp/chemacs/install.sh
fi

if [ -d ~/Projects/elisp/doom-emacs ]; then
    echo "~/.emacs.d already exists" 1>&2
else
    echo "Installing doom emacs"
    git clone https://github.com/hlissner/doom-emacs ~/Projects/elisp/doom-emacs
    ~/Projects/elisp/doom-emacs/bin/doom install
fi

if [ -e ~/.tmux-themepack ]; then
    echo "tmux-themepack is already installed"
else
    echo "Installing tmux-themepack"
    git clone https://github.com/jimeh/tmux-themepack.git ~/.tmux-themepack
fi

if [ -e ~/.fzf ]; then
    echo "fzf is already installed"
else
    echo "Installing fzf"
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install --no-update-rc --no-bash --no-zsh --no-fish
fi
