#!/bin/bash

if [ -d ~/.asdf ]; then
    echo "asdf is already installed"
else
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf
    ~/.asdf/bin/asdf plugin-add golang https://github.com/kennyp/asdf-golang.git
    ~/.asdf/bin/asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
    ~/.asdf/bin/asdf plugin-add lua https://github.com/Stratus3D/asdf-lua.git
    ~/.asdf/bin/asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    ~/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
fi
