# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9d193ad9-c3f4-4684-a472-a56582e556bb";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-a3559ae4-1c23-4922-878c-db39a621e900".device = "/dev/disk/by-uuid/a3559ae4-1c23-4922-878c-db39a621e900";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6708-9551";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # fileSystems."/data" =
  #   { device = "/dev/disk/by-uuid/eae86563-8920-47c6-9167-395dae8c6824";
  #     fsType = "ext4";
  #     options = [ "rw" "user" "exec" "uid=1000" "gid=1000" ];
  #   };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/09806ee8-707e-42b3-90f0-459c6973b9cc"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp34s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp40s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
