#!/bin/sh

if [ $1 = 'on' ];then
    emacsclient -e '(zezin-load-light-theme)' > /dev/null
    pkill -USR2 zsh
    echo light > $XDG_RUNTIME_DIR/theme
elif [ $1 = 'off' ]; then
    emacsclient -e '(zezin-load-dark-theme)' > /dev/null
    pkill -USR1 zsh
    echo dark > $XDG_RUNTIME_DIR/theme
fi